# Generated by Django 4.0.6 on 2023-04-23 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('devolvido', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.alunos')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.livros')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
            },
        ),
    ]
