# Generated by Django 4.0.6 on 2023-04-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emprestimos',
            new_name='Locacao',
        ),
    ]
