# Generated by Django 4.0.6 on 2023-04-23 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0002_rename_emprestimos_locacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={'verbose_name': 'Efetuar Locação', 'verbose_name_plural': 'Efetuar Locação'},
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 7, 23, 11, 29, 461730, tzinfo=utc), null=True),
        ),
    ]
