# Generated by Django 4.0.6 on 2023-04-23 23:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0004_alter_locacao_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 7, 23, 30, 4, 531586, tzinfo=utc), null=True),
        ),
    ]
