# Generated by Django 4.0.6 on 2023-04-23 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacao', '0003_alter_locacao_options_alter_locacao_data_devolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(default=django.utils.timezone.now)),
                ('locacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locacao.locacao')),
            ],
            options={
                'verbose_name': 'Efetuar Devolução',
                'verbose_name_plural': 'Efetuar Devolução',
            },
        ),
    ]
