# Generated by Django 4.0.6 on 2023-04-09 14:44

import cpf_field.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('ra', models.IntegerField(unique=True)),
                ('cpf', cpf_field.models.CPFField(blank=True, error_messages={'invalid': 'CPF inválido'}, max_length=11, unique=True)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('celular', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('sala', models.CharField(blank=True, max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=16, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('edicao', models.IntegerField()),
                ('qtd_disponivel', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='')),
                ('destaque', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.categorias')),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
