# Generated by Django 4.1.7 on 2023-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alunos_autores_categorias_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/img/livros/'),
        ),
    ]
