# Generated by Django 4.0.6 on 2023-04-16 00:58

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_livros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='C:\\Users\\fabri\\Documents\\PyCharmProjects\\iLibrary\\static/img/livros/', variations={'thumbnail': {'height': 350}}),
        ),
    ]
