# Generated by Django 4.1.7 on 2023-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_livros_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='cep',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
