# Generated by Django 4.0.6 on 2023-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_livros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(upload_to='livros/'),
        ),
    ]
