# Generated by Django 4.1.7 on 2023-04-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alunos_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='endereco',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='estado',
            new_name='uf',
        ),
        migrations.AddField(
            model_name='alunos',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
