# Generated by Django 4.1.7 on 2023-04-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_rename_endereco_alunos_complemento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='complemento',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='uf',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='logradouro',
        ),
    ]
