# Generated by Django 4.1.7 on 2023-04-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_rename_complemento_alunos_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
