# Generated by Django 4.1.7 on 2023-04-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alunos_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='imagem',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
